### ISSUE TITLE
http://localhost:5173 has no app

### ISSUE THREAD

**Issue by 0xCodeGuruX** [johnregan3/tars#7]
## Issue: http://localhost:5173 has no app
This is a great project, may I ask where did I go wrong? Everything went smoothly, but the application was not seen on the webpage in the end:

<img width="601" alt="Screenshot 2023-03-14 at 6 37 27 PM" src="https://user-images.githubusercontent.com/90074634/224974823-84727005-b5d9-458d-a189-df92f2149386.png">

## Env: 
Macbook Air M1
postgres (PostgreSQL) 15.2

✅Clone this repo.
✅Run composer install
✅Run npm install
✅php artisan migrate:fresh --seed
✅npm run build
✅npm run dev

### .env:
```
OPENAI_API_KEY=sk-
OPENAI_ORGANIZATION=
CHAT_USER_NAME=Cooper
CHAT_USER_ID=1
CHAT_TARS_NAME=TARS
CHAT_TARS_ID=2

DB_CONNECTION=pgsql
DB_HOST=mysql
DB_PORT=5432
DB_DATABASE=chat_database
DB_USERNAME=chat_user
DB_PASSWORD=password

CACHE_DRIVER=redis
APP_URL=http://localhost:8080
```

## Terminal:
  VITE v4.1.4  ready in 269 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

  LARAVEL v9.52.4  plugin v0.7.4

  ➜  APP_URL: http://localhost:8080

**Comment by johnregan3** [comment]
@RevAtN Thanks for the compliment!  I'm currently running this on Laravel Valet as my local webserver, and, frankly, I'm not all that familiar with using other options for that when running Laravel with Vite.   If you haven't you might [instal Valet](https://laravel.com/docs/10.x/valet#installation), then drop this repository into your `valet/` directory (wherever you put that), then the above stuff *should* work.

**Comment by johnregan3** [comment]
Here is a [similar forum thread](https://laracasts.com/discuss/channels/vite/laravel-vite-with-laravel-valet-on-local-network) that might give you a bit more information. YMMV.
Thanks for trying TARS out!
